version: '3'
services:
  central-library:
    container_name: central-library
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGADMIN_DEFAULT_EMAIL=s@nja.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    volumes:
      - pgadmin:/var/lib/pgadmin
volumes:
  data:
  pgadmin: