version: '3'
services:

  central-library:
    container_name: central-library
    image: sansansanya/central-library:docker
    ports:
      - "8000:8000"
    volumes:
      - ./central:/app
    depends_on:
      postgres:
        condition: service_healthy

  library-ns:
    container_name: library-ns
    image: sansansanya/local-library:docker
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8021
    ports:
      - "8021:8021"
    volumes:
      - ./local:/app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB=ns_db

  library-bg:
    container_name: library-bg
    image: sansansanya/local-library:docker
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8011
    ports:
      - "8011:8011"
    volumes:
      - ./local:/app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB=bg_db

  library-nis:
    container_name: library-nis
    image: sansansanya/local-library:docker
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8018
    ports:
      - "8018:8018"
    volumes:
      - ./local:/app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB=nis_db

  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=central_db,postgres:ns_db,postgres:bg_db,postgres:nis_db,postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - data:/var/lib/postgresql/data
      - ./docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
  
volumes:
  data:
  pgadmin: