apiVersion: apps/v1
kind: Deployment
metadata:
  name: bg-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bg-pod
  template:
    metadata:
      labels:
        app: bg-pod
    spec:
      volumes:
        - name: data-bg
          persistentVolumeClaim:
            claimName: pg-pvc
      containers:
        - name: bg-db
          image: sansansanya/cloud-db:k8s1.1
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: bg_db
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data-bg
              mountPath: /var/lib/postgresql/data
        - name: bg-library
          image: sansansanya/local-library:k8s1.2.6
          command:
            [
              "uvicorn",
              "main:app",
              "--reload",
              "--host",
              "0.0.0.0",
              "--port",
              "8011",
            ]
          ports:
            - containerPort: 8011
          env:
            - name: DB_HOST
              value: localhost
            - name: DB
              value: bg_db
            - name: OPENAPI_PREFIX
              value: bg
