apiVersion: v1
kind: Pod
metadata:
  name: bg-pod
spec:
  volumes:
    - name: data-bg
      persistentVolumeClaim:
        claimName: my-pvc
  containers:
    - name: postgres
      image: sansansanya/cloud-db:latest
      env:
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: bg_db
      ports:
        - containerPort: 5432
      volumeMounts:
        - name: data-bg
          mountPath: /var/lib/postgresql/data
    - name: bg-library
      image: sansansanya/local-library:k8s
      command:
        [
          "uvicorn",
          "main:app",
          "--reload",
          "--host",
          "0.0.0.0",
          "--port",
          "8011",
        ]
      ports:
        - containerPort: 8011
      env:
        - name: DB_HOST
          value: localhost
        - name: DB
          value: bg_db
