apiVersion: apps/v1
kind: Deployment
metadata:
  name: central-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: central-pod
  template:
    metadata:
      labels:
        app: central-pod
    spec:
      volumes:
        - name: data-central-3
          persistentVolumeClaim:
            claimName: my-pvc
      containers:
        - name: central-db
          image: sansansanya/cloud-db:k8s1.1
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: central_db
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data-central-3
              mountPath: /var/lib/postgresql/data
        - name: central-library
          image: sansansanya/central-library:2.2.0
          command:
            [
              "uvicorn",
              "main:app",
              "--reload",
              "--host",
              "0.0.0.0",
              "--port",
              "8000",
            ]
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: localhost
            - name: ROOT_PATH
              value: central
