apiVersion: apps/v1
kind: Deployment
metadata:
  name: central-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: central-pod
  template:
    metadata:
      labels:
        app: central-pod
    spec:
      volumes:
        - name: data-central
          persistentVolumeClaim:
            claimName: my-pvc
      containers:
        - name: central-db
          image: sansansanya/cloud-db:latest
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: central_db
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data-central
              mountPath: /var/lib/postgresql/data
          lifecycle:
            preStop:
              exec:
                command:
                  [
                    "/usr/local/bin/pg_ctl stop -D /var/lib/postgresql/data -w -t 60 -m fast",
                  ]
        - name: central-library
          image: sansansanya/central-library:k8s1.2.2
          command:
            [
              "uvicorn",
              "main:app",
              "--reload",
              "--host",
              "0.0.0.0",
              "--port",
              "8000",
            ]
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: localhost
