apiVersion: v1
kind: Service
metadata:
  name: central-library-service
spec:
  type: NodePort
  selector:
    app: central-library
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
