apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  labels:
    name: my-ingress
spec:
  rules:
    - host: library.cloud.io
      http:
        paths:
          - pathType: Prefix
            path: "/central"
            backend:
              service:
                name: central-service
                port:
                  number: 8000
          - pathType: Prefix
            path: "/ns"
            backend:
              service:
                name: ns-service
                port:
                  number: 8021
          - pathType: Prefix
            path: "/nis"
            backend:
              service:
                name: nis-service
                port:
                  number: 8018
          - pathType: Prefix
            path: "/bg"
            backend:
              service:
                name: bg-service
                port:
                  number: 8011
