apiVersion: apps/v1
kind: Deployment
metadata:
  name: nis-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nis-pod
  template:
    metadata:
      labels:
        app: nis-pod
    spec:
      volumes:
        - name: data-nis-3
          persistentVolumeClaim:
            claimName: my-pvc
      containers:
        - name: nis-db
          image: sansansanya/cloud-db:k8s1.1
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: nis_db
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data-nis-3
              mountPath: /var/lib/postgresql/data
        - name: nis-library
          image: sansansanya/local-library:2.2.0
          command:
            [
              "uvicorn",
              "main:app",
              "--reload",
              "--host",
              "0.0.0.0",
              "--port",
              "8018",
            ]
          ports:
            - containerPort: 8018
          env:
            - name: DB_HOST
              value: localhost
            - name: DB
              value: nis_db
            - name: ROOT_PATH
              value: nis
