apiVersion: v1
kind: Pod
metadata:
  name: ns-pod
spec:
  volumes:
    - name: data-ns
      persistentVolumeClaim:
        claimName: my-pvc
  containers:
    - name: ns-db
      image: sansansanya/cloud-db:latest
      env:
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: ns_db
      ports:
        - containerPort: 5433
      volumeMounts:
        - name: data-ns
          mountPath: /var/lib/postgresql/data
    - name: ns-library
      image: sansansanya/local-library:k8s
      command:
        [
          "uvicorn",
          "main:app",
          "--reload",
          "--host",
          "0.0.0.0",
          "--port",
          "8021",
        ]
      ports:
        - containerPort: 8021
      env:
        - name: DB_HOST
          value: localhost
        - name: DB
          value: ns_db
